name: Build Patched Rust Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Rust Toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build toolchain Docker image
        run: ./release.sh

      # - name: Copy distributable artifacts
      #   run: |
      #     mkdir -p dist

      #     docker cp \
      #       patched-rust-container:/workspace/rust/build/dist \
      #       ./dist

      # - name: Upload toolchain artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: patched-rust-toolchain
      #     path: dist
      #     retention-days: 1
