name: Build Rust Toolchain

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Rust Toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build toolchain
        run: ./release.sh

      - name: Upload toolchain artifacts
        uses: actions/upload-artifact@v4
        with:
          name: metacall-rust-toolchain
          path: dist/rust-toolchain.tar.gz
          retention-days: 1
